name: Tweet on Release

on:
  release:
    types: [published]  # Runs when a new release is published

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Post tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: "🚀 New GitHub Release: ${{ github.event.release.name }}! Check it out: ${{ github.event.release.html_url }}"
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
